TargetServer.class: TargetServer.java DoActionServlet.java LoginServlet.java ViewPageServlet.java
	javac -cp "./lib/*:." TargetServer.java DoActionServlet.java LoginServlet.java ViewPageServlet.java

run:
	java -Djava.ext.dirs=./lib TargetServer

clean:
	rm -f *.class

